#! /bin/bash

docker kill jekyll-site-from-github
docker rm jekyll-site-from-github

docker run -d -v /tmp/sitelogs:/site/logs -p 80 --name jekyll-site-from-github kamon/jekyll-site-from-github:latest kamon-io/kamon.io master
